// <auto-generated />
namespace ReportSpace.CustomerDashboard.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.0.0-beta1-20501")]
    public sealed partial class AddExtraFieldsOnUserProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExtraFieldsOnUserProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201307081220111_AddExtraFieldsOnUserProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
